[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "batch-data-ingestion-pipeline"
version = "0.1.0"

authors = [
    { name = "Daniel Doblas Jiménez", email = "dandobjim@gmail.com" }
]

maintainers = [
    { name = "Daniel Doblas Jiménez", email = "dandobjim@gmail.com" }
]

description = "A batch pipeline that extracts data from a public API and/or CSV sources, validates it against a schema, and lands it in a partitioned raw storage layer — fully orchestrated with Airflow."

readme = "README.md"

license = "Apache-2.0"
license-files = ["LICENSE"]

requires-python = ">=3.14"

keywords = ["batch", "elt", "parquet", "airflow"]

classifiers = [
    "Private :: Do Not Upload",
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Developers",
    "Topic :: Scientific/Engineering :: Information Analysis",
    "Programming Language :: Python :: 3.14"
]

dependencies = [
    "fastapi[standard]>=0.141.1",
    "pyarrow>=25.0.1",
    "requests>=2.34.2",
    "structlog>=26.1.0",
]

[project.urls]
Repository = "https://github.com/dandobjim/Batch-Ingestion-Pipeline"
Issues = "https://github.com/dandobjim/Batch-Ingestion-Pipeline/issues"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
    "ruff>=0.16.3",
]

[tool.hatch.build.targets.wheel]
packages = ["src/api", "src/elt"]

[tool.ruff]
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
]
line-length = 88
indent-width = 4
target-version = "py314"

[tool.ruff.lint]
select = ['E']
ignore = []
fixable = ["ALL"]
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-format = false
docstring-code-line-length = "dynamic"
